### ISSUE TITLE
Страница становится белой при введении неверного пароля при авторизации

### ISSUE THREAD

**Issue by Eron9** [nkiryanov/bbbs-qa#1]
Название: Страница становится белой при введении неверного пароля при авторизации
Шаги воспроизведения:
1.	Запустить программу 
2.	Нажать кнопку авторизации
3.	В строке "Логин" указать: bbbs
4.	В строке «Пароль» указать: Okjln256!
5.	Нажать кнопку «Войти»
Ожидаемый результат: Пользовать авторизовался на сайте
Фактический результат: Белая страница

https://user-images.githubusercontent.com/72934983/123643446-0c836e00-d82d-11eb-92a2-d2d72de06cfa.mp4

**Comment by nkiryanov** [comment]
Решено.
