### ISSUE TITLE
Дата не отдельной строкой в окне "Подтверждения записи на мероприятие"

### ISSUE THREAD

**Issue by Eron9** [nkiryanov/bbbs-qa#10]
**Шаги воспроизведения:**
   1. Авторизоваться в "Наставник. про" под валидными логином и паролем
   2. В поле "Календарь" выбрать мероприятие
   3. Нажать на кнопку "Записаться"
   4. В открывшемся окне подтвердить запись нажав кнопку "Подтвердить запись"

**Ожидаемый результат:** "Подтвердить запись на мероприятие", следующей строкой "Название мероприятия", следующая строка "Дата и время проведения" 
**Фактический результат:** "Название мероприятия" и "Дата и время проведения"  - идут одной строкой сливаясь
![дата с новой строки](https://user-images.githubusercontent.com/72934983/124614447-e8530d00-de7c-11eb-8c0c-6e829db5bee4.png)
![макет в 3 строчки](https://user-images.githubusercontent.com/72934983/124614450-e8eba380-de7c-11eb-9c09-8b20defa669a.png)

**Comment by EvanSidorenko** [comment]
Баг пофикшен, Наташ, закрой пжлста это ишью.
