### ISSUE TITLE
Элементы меню (Календарь Куда пойти Вопросы Читать и смотреть Права детей Истории) находятся в выпадающем меню в хедере главной страницы

### ISSUE THREAD

**Issue by EvanSidorenko** [nkiryanov/bbbs-qa#5]
*Шаги воспроизведения*:

1. Открыть главную страницу

*Ожидаемый результат*: Элементы меню отображены в хедере страницы одной строкой
*Фактический результат*: Элементы меню находяся в хедере страницы в выпадающем меню

*Окружение*: Chrome Version 91.0.4472.114 (Official Build) (64-bit), Microsoft Edge Версия 91.0.864.64 (64-разрядная версия), Firefox Browser 89.0.2 (64 - битный)

https://user-images.githubusercontent.com/83668360/124481341-d86df700-ddb0-11eb-9208-20867219d355.mp4

![Menu_header](https://user-images.githubusercontent.com/83668360/124481959-7f529300-ddb1-11eb-8b35-3b40e792a6d6.png)

**Comment by nkiryanov** [comment]
Вроде как решено уже. Относится к фронту и верстке. По-моему ожидаемое поведение.

**Comment by EvanSidorenko** [comment]
Да, решено. Просто у меня на ноуте отображается верстка для мобилок, т.к. экран не fullhd)
