### ISSUE TITLE
На странице куда пойти отсутсвует видимый для авторизированного пользователя блок "Порекомендовать место другим наставникам" 

### ISSUE THREAD

**Issue by EvanSidorenko** [nkiryanov/bbbs-qa#6]
*Описание*: После авторизации пользователя и перехода на страницу "Куда пойти" отсутсвует блок с ссылкой "заполните форму", при клике по которой открывается форма для создания места, рекомендуемого для посещения наставником.

*Шаги воспроизведения*:  
1. Открыть главную страницу
2. Авторизироваться
3. Перейти на страницу "Куда пойти"

*Фактический результат*: Авторизированный пользователь не видит блока "Порекомендовать место другим наставникам" 
*Ожидаемый результат*: Блок "Порекомендовать место другим наставникам"  отображаеся авторизированному пользователю.

*Окружение*: Chrome Version 91.0.4472.114 (Official Build) (64-bit), Microsoft Edge Версия 91.0.864.64 (64-разрядная версия), Firefox Browser 89.0.2 (64 - битный)

https://user-images.githubusercontent.com/83668360/124515539-64e7dc00-dde8-11eb-9ec3-d9d1e581041c.mp4

![Recomendation_form](https://user-images.githubusercontent.com/83668360/124515829-0e2ed200-dde9-11eb-8481-7b50105e611f.png)
![Visit_place_recom_form](https://user-images.githubusercontent.com/83668360/124515811-04a56a00-dde9-11eb-9cd3-af6fb1380aef.png)

**Comment by nkiryanov** [comment]
фронт
