### ISSUE TITLE
Нельзя отписаться от мероприятия в "Личном кабинете" наставника, только в "Календаре"

### ISSUE THREAD

**Issue by Eron9** [nkiryanov/bbbs-qa#7]
**Шаги воспроизведения:**

   Авторизоваться в "Наставник. про" под валидными логином и паролем
   В поле "Календарь" выбрать мероприятие
   Перейти в личный кабинет
   Кликнуть на выбранное ранее мероприятие
 
**Ожидаемый результат:** В левом нижнем углу есть кнопка "Отменить запись"

Фактический результат: В левом нижнем углу есть неактивная кнопка "Записаться

https://user-images.githubusercontent.com/72934983/124600221-29442500-de6f-11eb-8a57-2ec959b74fcf.mp4

"

**Comment by nkiryanov** [comment]
фронт

**Comment by EvanSidorenko** [comment]
Баг пофикшен, Наташ, закрой пжлста это ишью.
