### ISSUE TITLE
Разница с макетом в окне "Записи на мероприятие"

### ISSUE THREAD

**Issue by Eron9** [nkiryanov/bbbs-qa#8]
**Шаги воспроизведения:**

    1. Авторизоваться в "Наставник. про" под валидными логином и паролем
    2. В поле "Календарь" выбрать мероприятие
    3. Нажать на кнопку "Записаться"
    4. В открывшемся окне подтвердить запись нажав кнопку "Подтвердить запись"
    5. Обратить внимание на открывшееся окно

**Ожидаемый результат:** 1. Название мероприятия начинается с новой строки
2. Прописана дата и время мероприятия
3.  Между строкой "Если у вас не получится прийти — отмените, пожалуйста, запись." и кнопкой "Вернуться к календарю" есть пробел как на макете

**Фактический результат:** 1 Название идет на той же строке, что и фраза: "Вы записаны на мероприятие".
2. Даты и времени мероприятия нет
3. Между строкой "Если у вас не получится прийти — отмените, пожалуйста, запись." и кнопкой "Вернуться к календарю" пробела нет

![как в макете](https://user-images.githubusercontent.com/72934983/124606625-be4a1c80-de75-11eb-85bc-836ba56537a1.png)
![нет даты как в макете](https://user-images.githubusercontent.com/72934983/124606629-bee2b300-de75-11eb-81c1-29273bef36d4.png)

![нет пробелов в верстке](https://user-images.githubusercontent.com/72934983/124602331-67dadf00-de71-11eb-9453-d28bdb710c96.png)
![пробелы макет](https://user-images.githubusercontent.com/72934983/124602336-68737580-de71-11eb-8e5d-14545afa3985.png)

**Comment by nkiryanov** [comment]
фронт

**Comment by EvanSidorenko** [comment]
Баг пофикшен, Наташ, закрой пжлста это ишью.
