### ISSUE TITLE
Запись на мероприятие с главной страницы идет с ошибками

### ISSUE THREAD

**Issue by Eron9** [nkiryanov/bbbs-qa#9]
**Шаги воспроизведения:**

  1. Авторизоваться в "Наставник. про" под валидными логином и паролем
  2. На главной странице первое слева окно - мероприятие, обратить внимание на дату
  3. Нажать кнопку "Записаться"
  4. В новом окне нажать кнопку "Подтвердить запись" - **окно не выделилось**
  5. В следующем окне нажать кнопку "Вернуться к календарю" - **### по идее возвращаем в Календарь!**
  6. При нажатии на кнопку с тремя точками идет повторение пунктов с 3 по 5
  7. Переходим в личный кабинет

**Ожидаемый результат:** Видим событие на которое записались

**Фактический результат:** Мероприятия в списке нет. При возврате на главную страницу событие изменилось вместе с датой

https://user-images.githubusercontent.com/72934983/124613404-db81e980-de7b-11eb-9c3f-791226322614.mp4

**Comment by nkiryanov** [comment]
фронт

**Comment by EvanSidorenko** [comment]
Баг пофикшен, Наташ, закрой пжлста это ишью.
